#!/usr/bin/env bash
# Manages a daemon process

PIDFILE=/var/run/my_process.pid

start()
{
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo manage_my_process started
}

stop()
{
	pkill -SIGKILL -f ./manage_my_process
	rm "$PIDFILE"
	echo manage_my_process stopped
}

if [ "$1" = "start" ]; then
	start
elif [ "$1" = "stop" ]; then
	stop
elif [ "$1" = "restart" ]; then
	stop
	start
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
