#!/usr/bin/env bash
# Displays bad luck 4, good luck 8, to teach Chinese culture.
i=0
while [ $((i++)) -lt 10 ]; do
	echo Holberton School
	if [ $i -eq 4 ]; then
		echo bad luck
	elif [ $i -eq 8 ]; then
		echo good luck
	fi
done

