#!/usr/bin/env bash
# Uses cass for complex conditionals
i=0
while [ $((i++)) -lt 20 ]; do
	echo $i
	case $i in 4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	esac
done
