#! /usr/bin/env bash
# Checks file existence, emptiness, and regularity

file="holbertonschool"

if [ ! -e "$file" ]; then
	echo "$file" does not exist
	exit 0
fi
echo "$file" file exists

if [ -s "$file" ]; then
	echo "$file" is not empty
else
	echo "$file" is empty
fi

if [ -f "$file" ]; then
	echo "$file" is a regular file
fi
